---
title: "STA304 Paper"
author: "James Richards"
date: "11/03/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(knitr)
library(bookdown) # Referencing and report making
library(opendatatoronto) # Download data from here
library(dplyr) # Data manipulation
library(kableExtra) #Table displaying
library(tidyverse) # Data cleaning
library(ggthemes) # More plot themes
library(reshape2) # Dataframe merging
library(janitor) # Cleaning data
library(ggplot2) # To make graphs
```

## Loading in data
```{r}
Euro_data <- read_csv("Desktop/ESS1-9e01_1.csv")
```

## Data Cleaning
```{r}
##Creating new variable to categorize age
Euro_data <- tibble(Euro_data, agec = Euro_data$agea)
Euro_data$agec <-cut(Euro_data$agec, c(14,24,34,44,54,64,74,101), labels=c("15–24", "25–34", "35–44", "45–54"," 55–64", "65–74", "75+"))
Euro_data$agec <- as.factor(Euro_data$agec)

Euro_data$essround <- as.factor(Euro_data$essround)
```

## Exploring differences in responses over years
```{r}
## Creativity plot
ggplot(Euro_data, aes(x = factor(ipcrtiv), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Importance to think new ideas and be creative", subtitle = "How does creativity differ from 2002 to 2020", fill = "Ess Round")

## wealth plot
ggplot(Euro_data, aes(x = factor(imprich), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Importance of being rich, having money and expensive things", subtitle = "How does desire for wealth differ from 2002 to 2020", fill = "Ess Round")

## Equality plot
ggplot(Euro_data, aes(x = factor(ipeqopt), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Importance of people being treated equally and having equal opportunities", subtitle = "How do opinions on equality differ from 2002 to 2020", fill = "Ess Round")

## Abilities plot
ggplot(Euro_data, aes(x = factor(ipshabt), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to show abilities and be admired", subtitle = "How do opinions on showing off differ from 2002 to 2020", fill = "Ess Round")

## Safety plot
ggplot(Euro_data, aes(x = factor(impsafe), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to live in secure and safe surroundings", subtitle = "How do opinions on safety differ from 2002 to 2020", fill = "Ess Round")

## new plot
ggplot(Euro_data, aes(x = factor(impdiff), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to try new and different things in life", subtitle = "How do opinions on trying out things differ from 2002 to 2020", fill = "Ess Round")

## rules plot
ggplot(Euro_data, aes(x = factor(ipfrule), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to do what is told and follow rules", subtitle = "How do opinions on following rules differ from 2002 to 2020", fill = "Ess Round")

## understand plot
ggplot(Euro_data, aes(x = factor(ipudrst), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to understand different people", subtitle = "How do opinions on understanding people differ from 2002 to 2020", fill = "Ess Round")

## humble plot
ggplot(Euro_data, aes(x = factor(ipmodst), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to be humble and modest, not draw attention", subtitle = "How do opinions on humbleness differ from 2002 to 2020", fill = "Ess Round")

## fun plot
ggplot(Euro_data, aes(x = factor(ipgdtim), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to have a good time", subtitle = "How do opinions on having fun differ from 2002 to 2020", fill = "Ess Round")

## freedom plot
ggplot(Euro_data, aes(x = factor(impfree), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to make own decisions and be free", subtitle = "How do opinions on independence differ from 2002 to 2020", fill = "Ess Round")

## compassion plot
ggplot(Euro_data, aes(x = factor(iphlppl), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to help people and care for others well-being", subtitle = "How do opinions on compassion differ from 2002 to 2020", fill = "Ess Round")

## success plot
ggplot(Euro_data, aes(x = factor(ipsuces), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to be successful and that people recognise achievements", subtitle = "How do opinions on success differ from 2002 to 2020", fill = "Ess Round")

## government plot
ggplot(Euro_data, aes(x = factor(ipstrgv), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important that government is strong and ensures safety", subtitle = "How do opinions on government strength differ from 2002 to 2020", fill = "Ess Round")

## adventure plot
ggplot(Euro_data, aes(x = factor(ipadvnt), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to seek adventures and have an exciting life", subtitle = "How do opinions on an exciting life differ from 2002 to 2020", fill = "Ess Round")

## behavior plot
ggplot(Euro_data, aes(x = factor(ipbhprp), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to behave properly", subtitle = "How do opinions on proper behaviour differ from 2002 to 2020", fill = "Ess Round")

## respect plot
ggplot(Euro_data, aes(x = factor(iprspot), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to get respect from others", subtitle = "How do opinions on respect differ from 2002 to 2020", fill = "Ess Round")

## loyal plot
ggplot(Euro_data, aes(x = factor(iplylfr), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to be loyal to friends and devote to people close", subtitle = "How do opinions on loyalty differ from 2002 to 2020", fill = "Ess Round")

## nature plot
ggplot(Euro_data, aes(x = factor(impenv), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to care for nature and environment", subtitle = "How do opinions on caring for nature differ from 2002 to 2020", fill = "Ess Round")

## tradition plot
ggplot(Euro_data, aes(x = factor(imptrad), fill = essround)) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to follow traditions and customs", subtitle = "How do opinions on tradition differ from 2002 to 2020", fill = "Ess Round")

## pleasure plot
ggplot(Euro_data, aes(x = factor(impfun), fill = essround, label = (impfun))) +
    geom_bar() +
    theme_classic() +
  scale_fill_discrete(labels = c("Round 1", "Round 9")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to seek fun and things that give pleasure", subtitle = "How do opinions on pleasure differ from 2002 to 2020", fill = "Ess Round") + 
```


## age differences
```{r}
##how does age affect culture values in 2002 and 2020
Euro_data1 <-filter(Euro_data, essround == 1)
ggplot(Euro_data1, aes(x = factor(imptrad), fill = agec)) +
  geom_bar(position = position_dodge()) +
  theme_classic() +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to follow traditions and customs", subtitle = "How do opinions on tradition differ from between ages in 2002", fill = "Ess Round")

Euro_data2 <-filter(Euro_data, essround == 9)
ggplot(Euro_data2, aes(x = factor(imptrad), fill = agec)) +
  geom_bar(position = position_dodge()) +
  theme_classic() +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to follow traditions and customs", subtitle = "How do opinions on tradition differ from between ages in 2020", fill = "Ess Round")

##how does age affect government values in 2002 and 2020
ggplot(Euro_data1, aes(x = factor(ipstrgv), fill = agec)) +
  geom_bar(position = position_dodge()) +
  theme_classic() +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important that government is strong and ensures safety", subtitle = "How do opinions on government strength differ between ages in 2002", fill = "Ess Round")

ggplot(Euro_data2, aes(x = factor(ipstrgv), fill = agec)) +
  geom_bar(position = position_dodge()) +
  theme_classic() +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important that government is strong and ensures safety", subtitle = "How do opinions on government strength differ between ages in 2020", fill = "Ess Round")

##how does age affect government values in 2002 and 2020
ggplot(Euro_data1, aes(x = factor(impenv), fill = agec)) +
  geom_bar(position = position_dodge()) +
  theme_classic() +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
 labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to care for nature and environment", subtitle = "How do opinions on caring for nature differ between ages in 2002", fill = "Ess Round")

ggplot(Euro_data2, aes(x = factor(impenv), fill = agec)) +
  geom_bar(position = position_dodge()) +
  theme_classic() +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
 labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to care for nature and environment", subtitle = "How do opinions on caring for nature differ between ages in 2020", fill = "Ess Round")


##how does age affect success values in 2002 and 2020
ggplot(Euro_data1, aes(x = factor(ipsuces), fill = agec)) +
  geom_bar(position = position_dodge()) +
  theme_classic() +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to be successful and that people recognise achievements", subtitle = "How do opinions on success differ from 2002 to 2020", fill = "Ess Round")

ggplot(Euro_data2, aes(x = factor(ipsuces), fill = agec)) +
  geom_bar(position = position_dodge()) +
  theme_classic() +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) + 
  labs(x = "Level of agreement: 1 - Very much like me, 6 - not like me at all", title = "Important to be successful and that people recognise achievements", subtitle = "How do opinions on success differ from 2002 to 2020", fill = "Ess Round")
```




